### ISSUE TITLE
PROJECT INSIGHT

### ISSUE THREAD

**Issue by Kijacode** [Kijacode/mwengeSMS#16]
Bro  @alphaolomi  & @gsonly  can we have a **catch up cal**l , to discuss this project idea  🧙‍♂️??

**Comment by alphaolomi** [comment]
I suggest scheduling a google meet meeting

**Comment by Kijacode** [comment]
@alphaolomi  when are you suggesting ??

**Comment by alphaolomi** [comment]
> @alphaolomi  when are you suggesting ??

on sunday afternoon

**Comment by Kijacode** [comment]
@gsonly am waiting your suggestion .., in my side @alphaolomi  am okay with the time

**Comment by Kijacode** [comment]
Tomorrow at 10 pm we will meet link [here](https://meet.google.com/gaw-ynhd-vwx),  or you may give me your email ,then I can add you direct to the calender

**Comment by alphaolomi** [comment]
> Tomorrow at 10 pm we will meet link [here](https://meet.google.com/gaw-ynhd-vwx), or you may give me your email ,then I can add you direct to the calender

In addition to other agenda to be discussed  I want to point out that I have been working on an JS wrapper to [NextSMSplatform](https://nextsms.co.tz/) that offer bulk sms solution from 16TZS/per sms 

There are several option on the table
1. Africastalking
2. Bongolive  
3. Nextsms 

Link to repo https://github.com/nextsms/js-client 

Take a minute to review it.

**Comment by gsonly** [comment]
Did I miss the meeting? 🤦

**Comment by gsonly** [comment]
Did I miss the meeting? 🤦

**Comment by Kijacode** [comment]
> Did I miss the meeting? facepalm
Bro ni saa 10 mchana/jioni

**Comment by gsonly** [comment]
> > Did I miss the meeting? facepalm
> > Bro ni saa 10 mchana/jioni

:+1:

**Comment by Kijacode** [comment]
its time
