### ISSUE TITLE
improve code

### ISSUE THREAD

**Issue by gsonly** [Kijacode/mwengeSMS#7]
Hello, I'd like to submit a PR to improve your code... Hope you'll merge it! :smile:

**Comment by Kijacode** [comment]
Hello Bro @gsonly  ,thanks alot for this, I would sure merge them (I hope it a good work though )..........,your welcome to ;

1. Improve the code,
2. Add test,
3. Clead unused resources,
4. add documentation
5. so on,
Let work out for this and future repos 🕵️‍♂️.

**Comment by gsonly** [comment]
But what the project exactly **about**?
